package org.itson.bdavanzadas.agencia_fiscal_presentacion;

import java.text.NumberFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import org.itson.bdavanzadas.agencia_fiscal_bos.IRegistroLicenciaBO;
import org.itson.bdavanzadas.agencia_fiscal_bos.RegistroLicenciaBO;
import org.itson.bdavanzadas.agencia_fiscal_dtos.LicenciaNuevaDTO;
import org.itson.bdavanzadas.agencia_fiscal_dtos.PersonaNuevaDTO;
import org.itson.bdavanzadas.agencia_fiscal_excepciones_negocio.NegociosException;
import org.itson.bdavanzadas.agencia_fiscal_negocioAux.PreciosTramites;
import org.itson.bdavanzadas.agencia_fiscal_negocioAux.TipoLicencia;

public class PantallaTiposLicencias extends javax.swing.JDialog {

    /**
     * Creates new form PantallaTiposLicencias
     *
     * @param parent
     * @param modal
     * @param persona
     */
    public PantallaTiposLicencias(java.awt.Frame parent, boolean modal, PersonaNuevaDTO persona) {
        super(parent, modal);
        initComponents();
        this.persona = persona;
        this.registroLicencia = new RegistroLicenciaBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDosAnios = new javax.swing.JLabel();
        rbtDosAnios = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        lblTresAnios = new javax.swing.JLabel();
        rbtTresAnios = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        lblUnAnio = new javax.swing.JLabel();
        rbtUnAnio = new javax.swing.JRadioButton();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tramitar licencia");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(223, 223, 223));

        jPanel2.setBackground(new java.awt.Color(119, 119, 119));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 43)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("MÓDULO DE LICENCIAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblBienvenida.setFont(new java.awt.Font("Arial", 1, 29)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(119, 119, 119));
        lblBienvenida.setText("SELECCIONE UN TIPO DE LICENCIA");

        btnCancelar.setBackground(new java.awt.Color(159, 34, 65));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(159, 34, 65));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(156, 144));

        lblDosAnios.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblDosAnios.setForeground(new java.awt.Color(255, 255, 255));
        lblDosAnios.setText("2 AÑOS");

        rbtDosAnios.setBackground(new java.awt.Color(159, 34, 65));
        buttonGroup1.add(rbtDosAnios);
        rbtDosAnios.setForeground(new java.awt.Color(159, 34, 65));
        rbtDosAnios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtDosAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDosAniosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDosAnios)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(rbtDosAnios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblDosAnios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtDosAnios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(159, 34, 65));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(156, 144));

        lblTresAnios.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTresAnios.setForeground(new java.awt.Color(255, 255, 255));
        lblTresAnios.setText("3 AÑOS");

        rbtTresAnios.setBackground(new java.awt.Color(159, 34, 65));
        buttonGroup1.add(rbtTresAnios);
        rbtTresAnios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtTresAnios.setForeground(new java.awt.Color(159, 34, 65));
        rbtTresAnios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtTresAnios.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rbtTresAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTresAniosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTresAnios)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(rbtTresAnios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTresAnios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtTresAnios, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(159, 34, 65));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setPreferredSize(new java.awt.Dimension(156, 144));

        lblUnAnio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblUnAnio.setForeground(new java.awt.Color(255, 255, 255));
        lblUnAnio.setText("1 AÑO");

        rbtUnAnio.setBackground(new java.awt.Color(159, 34, 65));
        buttonGroup1.add(rbtUnAnio);
        rbtUnAnio.setForeground(new java.awt.Color(159, 34, 65));
        rbtUnAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtUnAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtUnAnioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblUnAnio)
                .addGap(39, 39, 39))
            .addComponent(rbtUnAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblUnAnio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtUnAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCosto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblCosto.setText("COSTO: ");

        txtCosto.setEditable(false);
        txtCosto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtCosto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCosto.setEnabled(false);

        btnAceptar.setBackground(new java.awt.Color(159, 34, 65));
        btnAceptar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 361, Short.MAX_VALUE)
                .addComponent(lblCosto)
                .addGap(18, 18, 18)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(lblBienvenida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblBienvenida)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Está en medio de un trámite, ¿desea salir en este momento?",
                "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (!txtCosto.getText().isBlank()) {
            registrarLicencia();
            JOptionPane.showMessageDialog(this, "Se ha registrado la licencia correctamente",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Asegúrese de seleccionar un tipo de licencia",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void rbtUnAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtUnAnioActionPerformed
        txtCosto.setText(NumberFormat.getCurrencyInstance().format(PreciosTramites.obtenerCostoLicencia(TipoLicencia.UN_ANIO, persona.isDiscapacitado())));
    }//GEN-LAST:event_rbtUnAnioActionPerformed

    private void rbtDosAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDosAniosActionPerformed
        txtCosto.setText(NumberFormat.getCurrencyInstance().format(PreciosTramites.obtenerCostoLicencia(TipoLicencia.DOS_ANIOS, persona.isDiscapacitado())));
    }//GEN-LAST:event_rbtDosAniosActionPerformed

    private void rbtTresAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTresAniosActionPerformed
        txtCosto.setText(NumberFormat.getCurrencyInstance().format(PreciosTramites.obtenerCostoLicencia(TipoLicencia.TRES_ANIOS, persona.isDiscapacitado())));
    }//GEN-LAST:event_rbtTresAniosActionPerformed

    private void registrarLicencia() {
        // Crea una fecha actual para calcular la fecha de vencimiento de la licencia
        Calendar fechaVencimiento = new GregorianCalendar();
        LicenciaNuevaDTO licenciaNueva = null;
        // Si se selecciona una licencia de un año
        if (rbtUnAnio.isSelected()) {
            // Se calcula la fecha de vecimiento sumando un año a la fecha actual
            fechaVencimiento.add(Calendar.YEAR, 1);
            // Si la persona es discapacitada
            Float costo = PreciosTramites.obtenerCostoLicencia(TipoLicencia.UN_ANIO, persona.isDiscapacitado());
            licenciaNueva = new LicenciaNuevaDTO(fechaVencimiento, new GregorianCalendar(),
                    costo, persona, true);
        }
        // Si se selecciona una licencia de dos años
        if (rbtDosAnios.isSelected()) {
            // Se calcula la fecha de vecimiento sumando dos años a la fecha actual
            fechaVencimiento.add(Calendar.YEAR, 2);
            // Si la persona es discapacitada
            Float costo = PreciosTramites.obtenerCostoLicencia(TipoLicencia.DOS_ANIOS, persona.isDiscapacitado());
            licenciaNueva = new LicenciaNuevaDTO(fechaVencimiento, new GregorianCalendar(),
                    costo, persona, true);
        }
        // Si se selecciona una licencia de tres años
        if (rbtTresAnios.isSelected()) {
            // Se calcula la fecha de vecimiento sumando tres años a la fecha actual
            fechaVencimiento.add(Calendar.YEAR, 3);
            // Si la persona es discapacitada
            Float costo = PreciosTramites.obtenerCostoLicencia(TipoLicencia.TRES_ANIOS, persona.isDiscapacitado());
            licenciaNueva = new LicenciaNuevaDTO(fechaVencimiento, new GregorianCalendar(),
                    costo, persona, true);
        }
        try {
            registroLicencia.tramitarLicencia(licenciaNueva);
        } catch (NegociosException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la licencia.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDosAnios;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTresAnios;
    private javax.swing.JLabel lblUnAnio;
    private javax.swing.JRadioButton rbtDosAnios;
    private javax.swing.JRadioButton rbtTresAnios;
    private javax.swing.JRadioButton rbtUnAnio;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables
    private IRegistroLicenciaBO registroLicencia;
    private PersonaNuevaDTO persona;
}
